server:
  port: 5555

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    quote-service: /quote/**
    rating-service: /rate/**
    policy-service:
      path: /policy/**
      url: http://localhost:9999

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
