spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mariadb://localhost:3306/nimi_quotes
    #url: jdbc:mariadb://192.168.99.100:3306/nimidb ->If running on Docker
    username: nimi #Credentials should be encrypted ->Use Hashicorp Vault/JCR encryption
    password: nimi #Credentials should be encrypted ->Use Hashicorp Vault/JCR encryption

hello:
  message: Hello DEFAULT Cloud YAML
