server:
  port: 8090

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

sidecar:
  hostname: localhost
  port: 9999
  health-uri: http://localhost:9999/health

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    policy-service:
      path: /policy/**
      url: http://localhost:9999

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
